### ISSUE TITLE
No module named 'gdbbridge'

### ISSUE THREAD

**Issue by kameamea** [csantosbh/gdb-imagewatch#36]
Since today I can't use gdb-imagewatch anymore. When I start gdb with
source /usr/local/bin/gdb-imagewatch/gdb-imagewatch.py in my .gdbinit

I get this error:

[gdb-imagewatch] Error: Exception thrown in qtcreator integration module
No module named 'gdbbridge'

and afterwards gdb is not accepting breakpoints anymore, i.e. is not really usable anymore.

I didn't change neither gdb (8.1) nor gdb-imagewatch (latest), so I assume, that ubuntu upgraded some python files which cause this new behaviour. As far as I can see only perl and ruby packages were updated however, so I have no idea where this error comes from.

**Comment by brunoalr** [comment]
This is happening to me too. I'm using Ubuntu 17.10.

**Comment by csantosbh** [comment]
Thank you all for reporting this issue!

This particular message shows up when the module that performs integration with QtCreator doesn't find the python modules of this IDE, but it should not be fatal by any means. I could not reproduce the breakpoint issue here, neither in QtCreator (v4.5.0) nor in raw gdb from the command line.

In any case, if you are experiencing this issue inside QtCreator, could you comment out line 62 of `gdb-imagewatch.py` and check if it works again? The line to be commented out looks like this:
```qtcreator.register_symbol_fetch_hook(event_handler.refresh_handler)```

At the very least, the error message should go away. Please let me know if that fixes the breakpoint issue as well.

**Comment by kameamea** [comment]
I uncommented the line so the error message disappeared, but the problem remains. 

Trying to reduce other influences I start gdb from the command line with no .gdbinit.
Then I set a breakpoint and then issue
`source /usr/local/bin/gdb-imagewatch/gdb-imagewatch.py`
Now I hit "next" and gdb crashes with segmentation fault.

No problems debugging without gdb-imagewatch, but my workflow depens so much on this great tool, that I can't really work without it. How can I help finding the issue behind this behaviour?

BTW: gdb-imagewatch --test works fine, so it's something between gdb and gdb-imagewatch which seems to be broken.

**Comment by kameamea** [comment]
I finally found the reason for my problem:
Because of other programs I had set those environment variables:
export MESA_GL_VERSION_OVERRIDE=3.3
export MESA_GLSL_VERSION_OVERRIDE=330

They cause gdb with gdb-imagewatch to crash with this stacktrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x00007ff7c34b3cf3 in GLCanvas::initializeGL() () from /home/rolf/soft/gdb-imagewatch/build/libgiwwindow.so
#2  0x00007ff7c2ee23cd in QGLWidget::glInit() () from /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#3  0x00007ff7c2ee83fc in QGLWidget::resizeEvent(QResizeEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#4  0x00007ff7c29d261e in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ff7c298f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ff7c2994516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ff7c209c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ff7c29caa41 in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ff7c29ce833 in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ff7c34ad965 in giw_create_window () from /home/rolf/soft/gdb-imagewatch/build/libgiwwindow.so
#24 0x00007ff7cff59e20 in ffi_call_unix64 () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#25 0x00007ff7cff5988b in ffi_call () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#26 0x00007ff7cff5401a in _ctypes_callproc () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#27 0x00007ff7cff47fcb in ?? () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#28 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#29 0x00007ff7d1bd192f in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#30 0x00007ff7d1c67cac in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#31 0x00007ff7d1c67d83 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#32 0x00007ff7d1aefbd5 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#33 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#34 0x00007ff7d1bd29eb in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#35 0x00007ff7d1bd7639 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#36 0x00007ff7d1bd7639 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#37 0x00007ff7d1c67cac in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#38 0x00007ff7d1c67d83 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#39 0x00007ff7d1aefad8 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#40 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#41 0x00007ff7d1c42aec in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#42 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#43 0x00007ff7d1c66937 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#44 0x00007ff7d1bffe12 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#45 0x00007ff7d23b46ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#46 0x00007ff7d0d7741d in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

Still wondering why gdb-imagewatch.sh --test works with those environment variables, but not within gdb.

**Comment by kameamea** [comment]
I finally found the reason for my problem:
Because of other programs I had set those environment variables:
export MESA_GL_VERSION_OVERRIDE=3.3
export MESA_GLSL_VERSION_OVERRIDE=330

They cause gdb with gdb-imagewatch to crash with this stacktrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x00007ff7c34b3cf3 in GLCanvas::initializeGL() () from /home/rolf/soft/gdb-imagewatch/build/libgiwwindow.so
#2  0x00007ff7c2ee23cd in QGLWidget::glInit() () from /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#3  0x00007ff7c2ee83fc in QGLWidget::resizeEvent(QResizeEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#4  0x00007ff7c29d261e in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ff7c298f05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ff7c2994516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ff7c209c38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ff7c29caa41 in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ff7c29ce833 in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ff7c29ce7c8 in QWidgetPrivate::showChildren(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ff7c29ce84f in QWidgetPrivate::show_helper() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ff7c29d163d in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ff7c34ad965 in giw_create_window () from /home/rolf/soft/gdb-imagewatch/build/libgiwwindow.so
#24 0x00007ff7cff59e20 in ffi_call_unix64 () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#25 0x00007ff7cff5988b in ffi_call () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#26 0x00007ff7cff5401a in _ctypes_callproc () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#27 0x00007ff7cff47fcb in ?? () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
#28 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#29 0x00007ff7d1bd192f in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#30 0x00007ff7d1c67cac in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#31 0x00007ff7d1c67d83 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#32 0x00007ff7d1aefbd5 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#33 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#34 0x00007ff7d1bd29eb in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#35 0x00007ff7d1bd7639 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#36 0x00007ff7d1bd7639 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#37 0x00007ff7d1c67cac in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#38 0x00007ff7d1c67d83 in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#39 0x00007ff7d1aefad8 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#40 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#41 0x00007ff7d1c42aec in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#42 0x00007ff7d1ba454e in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#43 0x00007ff7d1c66937 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#44 0x00007ff7d1bffe12 in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
#45 0x00007ff7d23b46ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#46 0x00007ff7d0d7741d in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

Still wondering why gdb-imagewatch.sh --test works with those environment variables, but not within gdb.
